version: '3'
services:
    nsqadmin:
        image: nsqio/nsq:latest
        command: ["./nsqadmin", "-nsqd-http-address", "nsqd:4151"]
        ports: 
            - "4171:4171"
        networks:
            search-net:

networks:
    search-net:
        external: true
