version: '3'
services:
    nsqd:
        image: nsqio/nsq:latest
        command: ["./nsqd"]
        ports: 
            - "4150:4150"
            - "4151:4151"
        networks:
            search-net:

networks:
    search-net:
        external: true
