version: '3'
services:
    postgres:
        image: postgres
        volumes:
          - ./fixtures/recipes.sql:/docker-entrypoint-initdb.d/recipes.sql
        ports: 
            - "5432:5432"
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
        - "5050:80"
        depends_on:
            - postgres
